"""airprompter-agent — run prompts and workflows approved in AirPrompter on your own systems.

::

    from airprompter_agent import AirPrompterAgent

    ap = AirPrompterAgent.start(organization_id="org_…", agent_id="agt_…", target="prod", api_key=os.environ["AIRPROMPTER_AGENT_KEY"], root={"pinned": PINNED_ROOT_JWK})
    rendered = ap.prompt("support.triage").render(team="Billing", ticket=ticket_text)
    completion = ap.observe(rendered, lambda: client.chat.completions.create(model=rendered.model, messages=[...]))
    ap.feedback(rendered.run_ref, thumbs="up")

Same protocol, same conformance vectors and the same on-disk store as the
TypeScript SDK; see the README for the parity matrix.
"""

from .agent import (
    PROTOCOL_VERSION,
    SDK_NAME,
    SDK_VERSION,
    AgentStartError,
    AgentStatus,
    AirPrompterAgent,
    ApplyOptions,
    PromptHandle,
    ReleaseChange,
    Rendered,
    RenderRefusedError,
    StagedRelease,
    SyncOptions,
    TelemetryOptions,
    VendoredBundle,
    Workflow,
    WorkflowStep,
    default_state_dir,
)
from .apply.window import UpdateWindow, WindowState, is_known_time_zone, parse_window, validate_window, window_state
from .bundle.apbundle import APBUNDLE_INFO, BundleError, DistributionKey, bundle_payload_bytes, create_encrypted_bundle, create_plaintext_bundle, distribution_key_id, open_bundle
from .bundle.hpke import X25519KeyPair, generate_x25519_key_pair, x25519_private_key_from_raw, x25519_public_key_from_raw
from .managed import MANAGED_REFUSAL_CODES, MANAGED_SDK_USER_AGENT, ManagedAgent, ManagedRunError, ManagedRunResult, ManagedRunStream, ManagedWorkflow, parse_sse
from .protocol import (
    ASSIGNMENT_MODULUS,
    UNDEFINED,
    Assignment,
    AssignmentError,
    CanonicalJsonError,
    StepError,
    Verdict,
    arm_for_bucket,
    assign_arm,
    bucket_from_hash,
    canonical_bytes,
    canonical_json,
    generate_p256_jwk,
    key_thumbprint,
    ordered_steps,
    public_jwk_of,
    referenced_payloads,
    release_digest,
    release_digest_input,
    sha256_prefixed,
    sign_bytes,
    subject_hash,
    trusted_root_from_pinned_key,
    validate_arms,
    verify_bytes,
    verify_manifest,
    verify_root_metadata,
)
from .render.run_ref import RunRefFacts, mint_run_ref, parse_run_ref
from .render.template import Delimiters, MissingVariableError, UnknownVariableError, render_template, xml_delimiters
from .spool.feedback import NormalizedFeedback, normalize_feedback
from .spool.writer import (
    ERROR_CLASSES,
    HOST_SPOOL_BUDGET_BYTES,
    LATENCY_BUCKET_EDGES_MS,
    SEGMENT_MAX_BYTES,
    SERVERLESS_BUFFER_BYTES,
    DirectorySink,
    MemorySink,
    Observation,
    SegmentPlanner,
    SpoolSink,
    SpoolWriter,
    WriterIdentity,
    epoch_minute,
    latency_bucket_index,
    minute_of,
    segment_name,
)
from .store.key_provider import KeyProvider, custom_key_provider, file_key, kms, os_keystore, unwrap_with_raw_key, vault, wrap_with_raw_key
from .store.payload_crypto import PayloadDecryptError, decrypt_payload, encrypt_payload, payload_aad
from .store.slot_store import LoadedSlot, SlotStore, StoreError, StoreHooks
from .sync.client import SyncClient
from .sync.daemon import DAEMON_MAX_LINE_BYTES, DaemonClient, DaemonError, DaemonHello, daemon_socket_path
from .sync.loop import SyncPassOutput, jittered_delay_ms, sync_once
from .checks import CHECK_BOUNDS, check_refusal, checks_refusals, estimate_tokens, evaluate_check, evaluate_checks, output_text_of, pattern_refusal, project_checks, validate_json_schema, value_at_path
from .telemetry.observe import ObserveTarget, UsageNormalized, classify_error, classify_result, normalize_usage, observe_call, observe_call_async

__version__ = SDK_VERSION

__all__ = [
    "APBUNDLE_INFO",
    "ASSIGNMENT_MODULUS",
    "AgentStartError",
    "AgentStatus",
    "AirPrompterAgent",
    "ApplyOptions",
    "Assignment",
    "AssignmentError",
    "BundleError",
    "CanonicalJsonError",
    "DAEMON_MAX_LINE_BYTES",
    "DaemonClient",
    "DaemonError",
    "DaemonHello",
    "Delimiters",
    "DirectorySink",
    "DistributionKey",
    "ERROR_CLASSES",
    "HOST_SPOOL_BUDGET_BYTES",
    "KeyProvider",
    "LATENCY_BUCKET_EDGES_MS",
    "LoadedSlot",
    "MANAGED_REFUSAL_CODES",
    "MANAGED_SDK_USER_AGENT",
    "ManagedAgent",
    "ManagedRunError",
    "ManagedRunResult",
    "ManagedRunStream",
    "ManagedWorkflow",
    "MemorySink",
    "MissingVariableError",
    "NormalizedFeedback",
    "Observation",
    "ObserveTarget",
    "PROTOCOL_VERSION",
    "PayloadDecryptError",
    "PromptHandle",
    "ReleaseChange",
    "RenderRefusedError",
    "Rendered",
    "RunRefFacts",
    "SDK_NAME",
    "SDK_VERSION",
    "SEGMENT_MAX_BYTES",
    "SERVERLESS_BUFFER_BYTES",
    "SegmentPlanner",
    "SlotStore",
    "SpoolSink",
    "SpoolWriter",
    "StagedRelease",
    "StepError",
    "StoreError",
    "StoreHooks",
    "SyncClient",
    "SyncOptions",
    "SyncPassOutput",
    "TelemetryOptions",
    "UNDEFINED",
    "UnknownVariableError",
    "UpdateWindow",
    "UsageNormalized",
    "VendoredBundle",
    "Verdict",
    "WindowState",
    "Workflow",
    "WorkflowStep",
    "WriterIdentity",
    "X25519KeyPair",
    "agent",
    "apply",
    "arm_for_bucket",
    "assign_arm",
    "bucket_from_hash",
    "bundle",
    "bundle_payload_bytes",
    "canonical_bytes",
    "canonical_json",
    "classify_error",
    "classify_result",
    "create_encrypted_bundle",
    "create_plaintext_bundle",
    "custom_key_provider",
    "daemon_socket_path",
    "decrypt_payload",
    "default_state_dir",
    "distribution_key_id",
    "encrypt_payload",
    "epoch_minute",
    "file_key",
    "generate_p256_jwk",
    "generate_x25519_key_pair",
    "is_known_time_zone",
    "jittered_delay_ms",
    "key_thumbprint",
    "kms",
    "latency_bucket_index",
    "managed",
    "mint_run_ref",
    "minute_of",
    "normalize_feedback",
    "normalize_usage",
    "observe_call",
    "observe_call_async",
    "CHECK_BOUNDS",
    "check_refusal",
    "checks_refusals",
    "estimate_tokens",
    "evaluate_check",
    "evaluate_checks",
    "output_text_of",
    "pattern_refusal",
    "project_checks",
    "validate_json_schema",
    "value_at_path",
    "open_bundle",
    "ordered_steps",
    "os_keystore",
    "parse_run_ref",
    "parse_sse",
    "parse_window",
    "payload_aad",
    "protocol",
    "public_jwk_of",
    "referenced_payloads",
    "release_digest",
    "release_digest_input",
    "render",
    "render_template",
    "segment_name",
    "sha256_prefixed",
    "sign_bytes",
    "spool",
    "store",
    "subject_hash",
    "sync",
    "sync_once",
    "telemetry",
    "trusted_root_from_pinned_key",
    "unwrap_with_raw_key",
    "validate_arms",
    "validate_window",
    "vault",
    "verify_bytes",
    "verify_manifest",
    "verify_root_metadata",
    "window_state",
    "wrap_with_raw_key",
    "x25519_private_key_from_raw",
    "x25519_public_key_from_raw",
    "xml_delimiters",
]
