// Reference implementation of the spool → OTLP mapping (S13), the smallest
// correct version of docs/telemetry.md › "Exporting to OpenTelemetry".
// `protocol/vectors/otel-mapping.json` (generated by the independent Python
// tool) pins it; every SDK's bridge must produce the same request.
//
//   const request = spoolRowsToOtlp(rows, { resource: { "service.name": "support-bot" } });   // one ExportMetricsServiceRequest, POST it as JSON

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const LATENCY_EDGES_MS = JSON.parse(readFileSync(join(existsSync(join(here, "..", "protocol", "schemas")) ? join(here, "..", "protocol") : join(here, "protocol"), "schemas", "latency-buckets.json"), "utf8")).edges;
const DELTA = 1;

const nanos = (iso) => `${Math.floor(Date.parse(iso) / 1000)}000000000`;
const attr = (key, value) =>
  typeof value === "boolean" ? { key, value: { boolValue: value } } : typeof value === "number" ? (Number.isInteger(value) ? { key, value: { intValue: String(value) } } : { key, value: { doubleValue: value } }) : { key, value: { stringValue: String(value) } };

function windowAttrs(row) {
  const attrs = [attr("gen_ai.request.model", row.model), attr("airprompter.prompt.tag", row.tag), attr("airprompter.prompt.version", row.versionId), attr("airprompter.prompt.arm", row.arm), attr("airprompter.status", row.status), attr("airprompter.usage.source", row.usageSource)];
  if (row.errorClass) attrs.push(attr("error.type", row.errorClass));
  return attrs;
}
const point = (value, attributes, start, end) => ({ attributes, startTimeUnixNano: start, timeUnixNano: end, asInt: String(Math.trunc(value)) });
const sum = (name, unit, dataPoints, description, monotonic = true) => ({ name, description, unit, sum: { aggregationTemporality: DELTA, isMonotonic: monotonic, dataPoints } });

export function spoolRowsToOtlp(rows, options = {}) {
  const first = rows[0];
  const [sdkName, sdkVersion] = String(first?.sdk ?? "").split("/");
  const resource = [attr("service.instance.id", first.instanceId)];
  if (first.instanceClass) resource.push(attr("airprompter.instance.class", first.instanceClass));
  if (sdkName) resource.push(attr("telemetry.sdk.name", sdkName));
  if (sdkVersion) resource.push(attr("telemetry.sdk.version", sdkVersion));
  for (const key of Object.keys(options.resource ?? {}).sort()) resource.push(attr(key, options.resource[key]));
  const duration = [], tokens = [], checks = [], feedbackN = [], feedbackSum = [], refusals = [], droppedSegments = [], droppedBytes = [];
  for (const row of rows) {
    if (row.type === "window") {
      const start = nanos(row.minute);
      const end = String(BigInt(start) + 60_000_000_000n);
      const attrs = windowAttrs(row);
      duration.push({ attributes: attrs, startTimeUnixNano: start, timeUnixNano: end, count: String(row.count), sum: row.latencyMs.sum / 1000, bucketCounts: row.latencyMs.buckets.map(String), explicitBounds: LATENCY_EDGES_MS.slice(0, -1).map((e) => e / 1000) });
      for (const [kind, value] of [["input", row.tokens.input ?? 0], ["cached_input", row.tokens.cachedInput ?? 0], ["output", row.tokens.output ?? 0]]) tokens.push(point(value, [...attrs, attr("gen_ai.token.type", kind)], start, end));
      if (row.checks) for (const outcome of ["passed", "failed"]) checks.push(point(row.checks[outcome], [...attrs, attr("airprompter.check.outcome", outcome)], start, end));
      for (const signal of Object.keys(row.outcomes ?? {}).sort()) {
        feedbackN.push(point(row.outcomes[signal].n, [...attrs, attr("airprompter.feedback.signal", signal)], start, end));
        feedbackSum.push({ attributes: [...attrs, attr("airprompter.feedback.signal", signal)], startTimeUnixNano: start, timeUnixNano: end, asDouble: Number(row.outcomes[signal].sum) });
      }
    } else if (row.type === "refusal") {
      const at = nanos(row.at);
      const attrs = [attr("airprompter.refusal.reason", row.reason), attr("airprompter.generation", row.generation)];
      if (row.tag) attrs.push(attr("airprompter.prompt.tag", row.tag));
      refusals.push(point(1, attrs, at, at));
    } else if (row.type === "dropped") {
      const at = nanos(row.at);
      droppedSegments.push(point(row.segments, [], at, at));
      droppedBytes.push(point(row.bytes, [], at, at));
    }
  }
  const metrics = [];
  if (duration.length) metrics.push({ name: "gen_ai.client.operation.duration", description: "Model call duration per prompt, version, arm and model; the spool's minute window as a delta histogram.", unit: "s", histogram: { aggregationTemporality: DELTA, dataPoints: duration } });
  if (tokens.length) metrics.push(sum("airprompter.tokens", "{token}", tokens, "Tokens per window by gen_ai.token.type (input, cached_input, output)."));
  if (checks.length) metrics.push(sum("airprompter.checks", "{check}", checks, "Declared output checks per window by outcome."));
  if (feedbackN.length) {
    metrics.push(sum("airprompter.feedback.count", "{signal}", feedbackN, "Feedback signals recorded per window."));
    metrics.push(sum("airprompter.feedback.sum", "1", feedbackSum, "The sum of a feedback signal's values per window (a rate is sum / count).", false));
  }
  if (refusals.length) metrics.push(sum("airprompter.refusals", "{refusal}", refusals, "Renders refused, by reason and generation."));
  if (droppedSegments.length) {
    metrics.push(sum("airprompter.spool.dropped_segments", "{segment}", droppedSegments, "Spool segments evicted by a budget: the loss, reported."));
    metrics.push(sum("airprompter.spool.dropped_bytes", "By", droppedBytes, "Bytes evicted by a budget."));
  }
  return { resourceMetrics: [{ resource: { attributes: resource }, scopeMetrics: [{ scope: { name: "airprompter", version: options.sdkVersion ?? "0.1.0" }, metrics }] }] };
}
