// Reference implementations of the two pure functions the protocol pins:
// canonical JSON (protocol/canonical-json.md) and sticky assignment
// (protocol/assignment-hash.md). Written from the prose, checked against the
// vectors, which were generated by an independent Python implementation.
// SDKs may copy these; they must pass the same vectors either way.
//
//   canonicalJson({ b: 1, a: [true, null] });                       // '{"a":[true,null],"b":1}'; a float or undefined throws CanonicalJsonError
//   sha256Prefixed(Buffer.from(canonicalJson(doc)));                // "sha256:…"
//   assignArm({ salt, subject: "user_42", arms: [{ arm: "control", weightBps: 9000 }, { arm: "candidate", weightBps: 1000 }] });   // { subjectHash, bucket, arm }

import { createHash } from "node:crypto";

export class CanonicalJsonError extends Error {
  constructor(reason, path) {
    super(`${reason} at ${path || "$"}`);
    this.reason = reason;
    this.path = path;
  }
}

const MAX_SAFE = Number.MAX_SAFE_INTEGER;

export function canonicalJson(value) {
  return encode(value, "$", new Set());
}

function encode(value, path, stack) {
  if (value === null) return "null";
  switch (typeof value) {
    case "boolean":
      return value ? "true" : "false";
    case "string":
      return JSON.stringify(value);
    case "number": {
      if (!Number.isFinite(value)) throw new CanonicalJsonError("non_finite_number", path);
      if (!Number.isInteger(value)) throw new CanonicalJsonError("non_integer_number", path);
      if (Math.abs(value) > MAX_SAFE) throw new CanonicalJsonError("unsafe_integer", path);
      return Object.is(value, -0) ? "0" : String(value);
    }
    case "undefined":
      throw new CanonicalJsonError("undefined_value", path);
    case "bigint":
    case "symbol":
    case "function":
      throw new CanonicalJsonError("unsupported_type", path);
    case "object":
      break;
    default:
      throw new CanonicalJsonError("unsupported_type", path);
  }
  if (stack.has(value)) throw new CanonicalJsonError("cycle", path);
  const proto = Object.getPrototypeOf(value);
  if (Array.isArray(value)) {
    stack.add(value);
    const parts = value.map((item, index) => encode(item, `${path}[${index}]`, stack));
    stack.delete(value);
    return `[${parts.join(",")}]`;
  }
  if (proto !== Object.prototype && proto !== null) throw new CanonicalJsonError("unsupported_type", path);
  stack.add(value);
  const keys = Object.keys(value).sort(); // default sort: UTF-16 code units
  const parts = [];
  for (const key of keys) {
    parts.push(`${JSON.stringify(key)}:${encode(value[key], `${path}.${key}`, stack)}`);
  }
  stack.delete(value);
  return `{${parts.join(",")}}`;
}

export function sha256Prefixed(bytes) {
  return `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
}

/** The digest input: pins sorted by tag, projected to exactly the covered members. */
export const INFERENCE_DIGEST_KEYS = ["maxOutputTokens", "reasoningEffort", "stopSequences", "temperatureMilli", "topPBps"];

/** The inference block as the digest covers it: the known keys, each only when set. */
export function inferenceDigestInput(inference) {
  return Object.fromEntries(INFERENCE_DIGEST_KEYS.filter((k) => inference[k] !== undefined && inference[k] !== null).map((k) => [k, inference[k]]));
}

export function releaseDigestInput(slots) {
  return [...slots]
    .sort((a, b) => (a.tag < b.tag ? -1 : a.tag > b.tag ? 1 : 0))
    .map((slot) => ({
      tag: slot.tag,
      kind: slot.kind,
      artifactId: slot.artifactId,
      versionId: slot.versionId,
      versionOrdinal: slot.versionOrdinal,
      contentHash: slot.contentHash,
      byteLength: slot.byteLength,
      model: slot.model,
      ...(slot.modelRequired === true ? { modelRequired: true } : {}),
      ...(Array.isArray(slot.outputChecks) && slot.outputChecks.length > 0 ? { outputChecks: slot.outputChecks } : {}),
      ...(slot.goldenSet ? { goldenSet: { setId: slot.goldenSet.setId, cases: slot.goldenSet.cases, contentHash: slot.goldenSet.contentHash, byteLength: slot.goldenSet.byteLength, minPassBps: slot.goldenSet.minPassBps } } : {}),
      // 0.3.1: the inference block is digest-bound when present — its known keys, each only when set (a JSON null is unset).
      ...(slot.inference ? { inference: inferenceDigestInput(slot.inference) } : {}),
      // 0.3.4: `default` and `source` ride the digest only when the pin carries them, so a slot without them keeps its digest.
      variables: slot.variables.map((v) => ({ name: v.name, required: v.required, trust: v.trust, ...(v.default !== undefined && v.default !== null ? { default: v.default } : {}), ...(v.source !== undefined && v.source !== null ? { source: v.source } : {}) })),
      ...(slot.steps
        ? {
            steps: slot.steps.map((s) => ({
              stepId: s.stepId,
              ordinal: s.ordinal,
              promptArtifactId: s.promptArtifactId,
              promptVersionId: s.promptVersionId,
              contentHash: s.contentHash,
              byteLength: s.byteLength,
              // 0.3.2: a step's own settings, projected as a slot's are.
              ...(s.inference ? { inference: inferenceDigestInput(s.inference) } : {}),
            })),
          }
        : {}),
    }));
}

export function releaseDigest(slots) {
  return sha256Prefixed(Buffer.from(canonicalJson(releaseDigestInput(slots)), "utf8"));
}

// ---------------------------------------------------------------------------
// Sticky assignment
// ---------------------------------------------------------------------------

const BASE64URL = /^[A-Za-z0-9_-]+$/;
export const ASSIGNMENT_MODULUS = 10000;

export class AssignmentError extends Error {
  constructor(reason) {
    super(reason);
    this.reason = reason;
  }
}

export function decodeBase64Url(text) {
  if (!BASE64URL.test(text)) throw new AssignmentError("salt_invalid");
  return Buffer.from(text, "base64url");
}

export function validateArms(arms) {
  if (!Array.isArray(arms) || arms.length < 2) throw new AssignmentError("too_few_arms");
  let total = 0;
  for (const arm of arms) {
    if (!Number.isInteger(arm.weightBps) || arm.weightBps < 0) throw new AssignmentError("weight_invalid");
    total += arm.weightBps;
  }
  if (total !== ASSIGNMENT_MODULUS) throw new AssignmentError("weights_not_10000");
}

export function subjectHash(salt, subject) {
  const saltBytes = decodeBase64Url(salt);
  if (saltBytes.length < 16) throw new AssignmentError("salt_invalid");
  return createHash("sha256").update(saltBytes).update(Buffer.from(subject, "utf8")).digest("hex");
}

export function bucketFromHash(hex) {
  // First eight bytes as an unsigned 64-bit big-endian integer, reduced mod 10000.
  const value = BigInt(`0x${hex.slice(0, 16)}`);
  return Number(value % BigInt(ASSIGNMENT_MODULUS));
}

export function assignArm({ salt, subject, arms }) {
  validateArms(arms);
  const hash = subjectHash(salt, subject);
  const bucket = bucketFromHash(hash);
  let cumulative = 0;
  for (const arm of arms) {
    cumulative += arm.weightBps;
    if (bucket < cumulative) return { subjectHash: hash, bucket, arm: arm.arm };
  }
  throw new AssignmentError("weights_not_10000");
}

// ---------------------------------------------------------------------------
// Workflow steps
// ---------------------------------------------------------------------------

const SLOT_TAG = /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/;

export function orderedSteps(slotTag, steps) {
  if (!SLOT_TAG.test(slotTag)) throw new AssignmentError("slot_tag_grammar");
  const sorted = [...steps].sort((a, b) => a.ordinal - b.ordinal);
  sorted.forEach((step, index) => {
    if (step.ordinal !== index + 1) throw new AssignmentError("step_ordinal_gap");
    if (step.stepId !== `${slotTag}#${step.ordinal}`) throw new AssignmentError("step_tag_mismatch");
  });
  return sorted;
}

// ---------------------------------------------------------------------------
// S9: the signed ramp plan (assignment-hash.md › The ramp plan)
// ---------------------------------------------------------------------------

export const RAMP_MIN_STEP_MS = 60 * 60 * 1000;
export const RAMP_MAX_STEPS = 8;

export function validateRamp(ramp, armCount) {
  if (ramp === undefined) return;
  if (!Array.isArray(ramp) || ramp.length < 1 || ramp.length > RAMP_MAX_STEPS) throw new AssignmentError("ramp_invalid");
  let previous = null;
  for (const step of ramp) {
    if (!step || typeof step !== "object" || typeof step.notBefore !== "string" || !Array.isArray(step.weightBps)) throw new AssignmentError("ramp_invalid");
    const at = Date.parse(step.notBefore);
    if (!Number.isFinite(at)) throw new AssignmentError("ramp_invalid");
    if (previous !== null && at - previous < RAMP_MIN_STEP_MS) throw new AssignmentError("ramp_invalid");
    previous = at;
    if (step.weightBps.length !== armCount) throw new AssignmentError("ramp_invalid");
    let total = 0;
    for (const weight of step.weightBps) {
      if (!Number.isInteger(weight) || weight < 0) throw new AssignmentError("ramp_invalid");
      total += weight;
    }
    if (total !== ASSIGNMENT_MODULUS) throw new AssignmentError("ramp_invalid");
  }
}

export function rampWeightsAt(arms, ramp, nowMs) {
  let weights = arms.map((arm) => arm.weightBps);
  for (const step of ramp ?? []) if (Date.parse(step.notBefore) <= nowMs) weights = [...step.weightBps];
  return weights;
}

export function effectiveArms({ arms, ramp, disabledArms, nowMs }) {
  const weights = rampWeightsAt(arms, ramp, nowMs);
  const disabled = disabledArms ?? new Set();
  const firstLive = arms.findIndex((arm) => !disabled.has(arm.arm));
  if (firstLive === -1) return null;
  let reassigned = 0;
  const effective = arms.map((arm, index) => {
    if (!disabled.has(arm.arm)) return { ...arm, weightBps: weights[index] };
    reassigned += weights[index];
    return { ...arm, weightBps: 0 };
  });
  effective[firstLive] = { ...effective[firstLive], weightBps: effective[firstLive].weightBps + reassigned };
  return effective;
}
