// Reference implementations of the two pure functions the protocol pins:
// canonical JSON (protocol/canonical-json.md) and sticky assignment
// (protocol/assignment-hash.md). Written from the prose, checked against the
// vectors, which were generated by an independent Python implementation.
// SDKs may copy these; they must pass the same vectors either way.

import { createHash } from "node:crypto";

export class CanonicalJsonError extends Error {
  constructor(reason, path) {
    super(`${reason} at ${path || "$"}`);
    this.reason = reason;
    this.path = path;
  }
}

const MAX_SAFE = Number.MAX_SAFE_INTEGER;

export function canonicalJson(value) {
  return encode(value, "$", new Set());
}

function encode(value, path, stack) {
  if (value === null) return "null";
  switch (typeof value) {
    case "boolean":
      return value ? "true" : "false";
    case "string":
      return JSON.stringify(value);
    case "number": {
      if (!Number.isFinite(value)) throw new CanonicalJsonError("non_finite_number", path);
      if (!Number.isInteger(value)) throw new CanonicalJsonError("non_integer_number", path);
      if (Math.abs(value) > MAX_SAFE) throw new CanonicalJsonError("unsafe_integer", path);
      return Object.is(value, -0) ? "0" : String(value);
    }
    case "undefined":
      throw new CanonicalJsonError("undefined_value", path);
    case "bigint":
    case "symbol":
    case "function":
      throw new CanonicalJsonError("unsupported_type", path);
    case "object":
      break;
    default:
      throw new CanonicalJsonError("unsupported_type", path);
  }
  if (stack.has(value)) throw new CanonicalJsonError("cycle", path);
  const proto = Object.getPrototypeOf(value);
  if (Array.isArray(value)) {
    stack.add(value);
    const parts = value.map((item, index) => encode(item, `${path}[${index}]`, stack));
    stack.delete(value);
    return `[${parts.join(",")}]`;
  }
  if (proto !== Object.prototype && proto !== null) throw new CanonicalJsonError("unsupported_type", path);
  stack.add(value);
  const keys = Object.keys(value).sort(); // default sort: UTF-16 code units
  const parts = [];
  for (const key of keys) {
    parts.push(`${JSON.stringify(key)}:${encode(value[key], `${path}.${key}`, stack)}`);
  }
  stack.delete(value);
  return `{${parts.join(",")}}`;
}

export function sha256Prefixed(bytes) {
  return `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
}

/** The digest input: pins sorted by tag, projected to exactly the covered members. */
export function releaseDigestInput(slots) {
  return [...slots]
    .sort((a, b) => (a.tag < b.tag ? -1 : a.tag > b.tag ? 1 : 0))
    .map((slot) => ({
      tag: slot.tag,
      kind: slot.kind,
      artifactId: slot.artifactId,
      versionId: slot.versionId,
      versionOrdinal: slot.versionOrdinal,
      contentHash: slot.contentHash,
      byteLength: slot.byteLength,
      model: slot.model,
      ...(slot.modelRequired === true ? { modelRequired: true } : {}),
      variables: slot.variables.map((v) => ({ name: v.name, required: v.required, trust: v.trust })),
      ...(slot.steps
        ? {
            steps: slot.steps.map((s) => ({
              stepId: s.stepId,
              ordinal: s.ordinal,
              promptArtifactId: s.promptArtifactId,
              promptVersionId: s.promptVersionId,
              contentHash: s.contentHash,
              byteLength: s.byteLength,
            })),
          }
        : {}),
    }));
}

export function releaseDigest(slots) {
  return sha256Prefixed(Buffer.from(canonicalJson(releaseDigestInput(slots)), "utf8"));
}

// ---------------------------------------------------------------------------
// Sticky assignment
// ---------------------------------------------------------------------------

const BASE64URL = /^[A-Za-z0-9_-]+$/;
export const ASSIGNMENT_MODULUS = 10000;

export class AssignmentError extends Error {
  constructor(reason) {
    super(reason);
    this.reason = reason;
  }
}

export function decodeBase64Url(text) {
  if (!BASE64URL.test(text)) throw new AssignmentError("salt_invalid");
  return Buffer.from(text, "base64url");
}

export function validateArms(arms) {
  if (!Array.isArray(arms) || arms.length < 2) throw new AssignmentError("too_few_arms");
  let total = 0;
  for (const arm of arms) {
    if (!Number.isInteger(arm.weightBps) || arm.weightBps < 0) throw new AssignmentError("weight_invalid");
    total += arm.weightBps;
  }
  if (total !== ASSIGNMENT_MODULUS) throw new AssignmentError("weights_not_10000");
}

export function subjectHash(salt, subject) {
  const saltBytes = decodeBase64Url(salt);
  if (saltBytes.length < 16) throw new AssignmentError("salt_invalid");
  return createHash("sha256").update(saltBytes).update(Buffer.from(subject, "utf8")).digest("hex");
}

export function bucketFromHash(hex) {
  // First eight bytes as an unsigned 64-bit big-endian integer, reduced mod 10000.
  const value = BigInt(`0x${hex.slice(0, 16)}`);
  return Number(value % BigInt(ASSIGNMENT_MODULUS));
}

export function assignArm({ salt, subject, arms }) {
  validateArms(arms);
  const hash = subjectHash(salt, subject);
  const bucket = bucketFromHash(hash);
  let cumulative = 0;
  for (const arm of arms) {
    cumulative += arm.weightBps;
    if (bucket < cumulative) return { subjectHash: hash, bucket, arm: arm.arm };
  }
  throw new AssignmentError("weights_not_10000");
}

// ---------------------------------------------------------------------------
// Workflow steps
// ---------------------------------------------------------------------------

const SLOT_TAG = /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/;

export function orderedSteps(slotTag, steps) {
  if (!SLOT_TAG.test(slotTag)) throw new AssignmentError("slot_tag_grammar");
  const sorted = [...steps].sort((a, b) => a.ordinal - b.ordinal);
  sorted.forEach((step, index) => {
    if (step.ordinal !== index + 1) throw new AssignmentError("step_ordinal_gap");
    if (step.stepId !== `${slotTag}#${step.ordinal}`) throw new AssignmentError("step_tag_mismatch");
  });
  return sorted;
}
