#!/usr/bin/env node
// The compatibility table (S10): per package, which protocol vectors its
// suites run and whether they pass — generated from the conformance run,
// never typed by hand. Writes the table between the markers in
// `sdk-typescript/README.md` and the repository README; `--check` exits 1
// when either file is stale (CI runs the check; a contributor runs the
// generator).

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const repo = resolve(root, "..");
const protocolVersion = readFileSync(join(repo, "protocol", "VERSION"), "utf8").trim();

/** Which suites exercise which protocol vectors, per package. A suite is named once, under the package it tests. */
const PACKAGES = {
  core: {
    suites: ["protocolVectors", "ramp", "render", "golden", "hpke", "discriminants"],
    vectors: ["canonical-json.json", "manifest-verify.json", "assignment.json", "ramp.json", "workflow-steps.json", "checks.json"],
  },
  sync: { suites: ["store", "storeFormat", "apply", "policy", "pointer"], vectors: ["examples/store.v1.json", "examples/store.v2.json", "examples/refused/*"] },
  runtime: { suites: ["wrap", "managed", "packageSplit"], vectors: ["ramp.json (walked by `ReleaseResolver` over a bundle release)"] },
  telemetry: { suites: ["spool", "spoolFaults", "uploader", "budgetInvariant"], vectors: ["spool.json", "feedback.json"] },
  "otel-bridge": { suites: ["otelBridge"], vectors: ["otel-mapping.json"] },
  sdk: { suites: ["agent", "vendored", "uploadHost", "telemetry"], vectors: ["examples/heartbeat.*.json", "examples/edge-pointer.json"] },
};

function runSuites(names) {
  const files = names.map((name) => join(root, "test", `${name}.test.ts`));
  const result = spawnSync(process.execPath, ["--import", "tsx", "--test", ...files], { cwd: root, encoding: "utf8", env: { ...process.env, FORCE_COLOR: "0" } });
  const passed = Number(/^ℹ pass (\d+)/m.exec(result.stdout)?.[1] ?? 0);
  const failed = Number(/^ℹ fail (\d+)/m.exec(result.stdout)?.[1] ?? 0);
  return { ok: result.status === 0 && failed === 0, passed, failed };
}

function table() {
  const version = JSON.parse(readFileSync(join(root, "packages", "core", "package.json"), "utf8")).version;
  const rows = [];
  for (const [name, { suites, vectors }] of Object.entries(PACKAGES)) {
    const result = runSuites(suites);
    rows.push(`| \`${name === "otel-bridge" ? "@airprompter/otel-bridge" : `@airprompter/agent-${name}`}\` | ${version} | ${protocolVersion} | ${vectors.map((v) => `\`${v}\``).join(", ")} | ${result.ok ? "green" : `**red** (${result.failed} failing)`} |`);
  }
  return [
    "| Package | Version | Protocol | Vectors and examples exercised | Conformance |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    `Generated by \`sdk-typescript/scripts/compat-table.mjs\` from the conformance run on protocol \`${protocolVersion}\` (Node ${process.versions.node.split(".")[0]}). One version across the six packages; \`@airprompter/agent-sdk\` exact-pins its siblings; \`@airprompter/otel-bridge\` is optional and pins core.`,
  ].join("\n");
}

const START = "<!-- compat-table:start -->";
const END = "<!-- compat-table:end -->";

function splice(path, body) {
  const text = readFileSync(path, "utf8").replace(/\r\n/g, "\n");
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start === -1 || end === -1) throw new Error(`${path}: no compat-table markers`);
  return text.slice(0, start + START.length) + "\n" + body + "\n" + text.slice(end);
}

const body = table();
const targets = [join(root, "README.md"), join(repo, "README.md")];
let stale = false;
for (const path of targets) {
  const next = splice(path, body);
  const current = readFileSync(path, "utf8");
  // The Node major in the footer is environment, and a Windows checkout may carry CRLF; a check compares everything else.
  const strip = (s) => s.replace(/\r\n/g, "\n").replace(/\(Node \d+\)/g, "(Node N)");
  if (strip(next) !== strip(current)) {
    stale = true;
    if (!process.argv.includes("--check")) writeFileSync(path, next);
  }
}
if (process.argv.includes("--check")) {
  if (stale) {
    console.error("compat-table: the README table is stale; run `npm run compat-table` in sdk-typescript");
    process.exit(1);
  }
  console.log("compat-table: fresh");
} else {
  console.log(body);
}

