"""airprompter-agent — run prompts and workflows approved in AirPrompter on your own systems.

::

    from airprompter_agent import AirPrompterAgent

    ap = AirPrompterAgent.start(organization_id="org_…", agent_id="agt_…", target="prod", api_key=os.environ["AIRPROMPTER_AGENT_KEY"], root={"pinned": PINNED_ROOT_JWK})
    rendered = ap.prompt("support.triage").render(team="Billing", ticket=ticket_text)
    completion = ap.observe(rendered, lambda: client.chat.completions.create(model=rendered.model, messages=[...]))
    ap.feedback(rendered.run_ref, thumbs="up")

Same protocol, same conformance vectors and the same on-disk store as the
TypeScript SDK; see the README for the parity matrix.
"""

from .agent import (
    PROTOCOL_VERSION,
    SDK_NAME,
    SDK_VERSION,
    AgentStartError,
    AgentStatus,
    AirPrompterAgent,
    ApplyOptions,
    GoldenOptions,
    PromptHandle,
    ReleaseChange,
    Rendered,
    RenderRefusedError,
    StagedRelease,
    SyncOptions,
    TelemetryOptions,
    VendoredBundle,
    Workflow,
    WorkflowHandle,
    WorkflowStep,
    default_state_dir,
    healthz_of,
    healthz_response,
)
from airprompter_agent_sync.apply.window import UpdateWindow, WindowState, is_known_time_zone, parse_window, validate_window, window_state
from airprompter_agent_core.golden import GOLDEN_SET_FORMAT, GOLDEN_SET_VERSION, GoldenCaseResult, GoldenInvocation, GoldenReport, GoldenSetError, golden_reports_meet, parse_golden_set, pass_bps_of, run_golden_set
from airprompter_agent_core.judge import JUDGE_RUBRICS, PROTECTION_CRITERIA, JudgeResult, JudgeRubric, judge_prompt, judge_signals_of, parse_judge_reply, rubric_from_prompt
from airprompter_agent_core.bundle.apbundle import APBUNDLE_INFO, BundleError, DistributionKey, bundle_payload_bytes, create_encrypted_bundle, create_plaintext_bundle, distribution_key_id, open_bundle
from airprompter_agent_core.bundle.hpke import X25519KeyPair, generate_x25519_key_pair, x25519_private_key_from_raw, x25519_public_key_from_raw
from airprompter_agent_runtime.managed import MANAGED_REFUSAL_CODES, MANAGED_SDK_USER_AGENT, ManagedAgent, ManagedRunError, ManagedRunResult, ManagedRunStream, ManagedWorkflow, parse_sse
from airprompter_agent_core.protocol import (
    ASSIGNMENT_MODULUS,
    UNDEFINED,
    Assignment,
    AssignmentError,
    CanonicalJsonError,
    StepError,
    Verdict,
    arm_for_bucket,
    assign_arm,
    bucket_from_hash,
    canonical_bytes,
    canonical_json,
    generate_p256_jwk,
    key_thumbprint,
    ordered_steps,
    public_jwk_of,
    referenced_payloads,
    release_digest,
    release_digest_input,
    sha256_prefixed,
    sign_bytes,
    subject_hash,
    trusted_root_from_pinned_key,
    validate_arms,
    verify_bytes,
    verify_manifest,
    verify_root_metadata,
)
from airprompter_agent_core.render.run_ref import RunRefFacts, mint_run_ref, parse_run_ref
from airprompter_agent_core.render.template import Delimiters, MissingVariableError, UnknownVariableError, render_template, xml_delimiters
from airprompter_agent_core.telemetry.feedback import NormalizedFeedback, normalize_feedback
from airprompter_agent_telemetry.spool.writer import (
    ERROR_CLASSES,
    HOST_SPOOL_BUDGET_BYTES,
    LATENCY_BUCKET_EDGES_MS,
    SEGMENT_MAX_BYTES,
    SERVERLESS_BUFFER_BYTES,
    DirectorySink,
    MemorySink,
    Observation,
    SegmentPlanner,
    SpoolSink,
    SpoolWriter,
    WriterIdentity,
    epoch_minute,
    latency_bucket_index,
    minute_of,
    segment_name,
)
from airprompter_agent_sync.store.key_provider import KeyProvider, custom_key_provider, file_key, kms, os_keystore, unwrap_with_raw_key, vault, wrap_with_raw_key
from airprompter_agent_sync.store.payload_crypto import PayloadDecryptError, decrypt_payload, encrypt_payload, payload_aad
from airprompter_agent_sync.store.slot_store import LoadedSlot, SlotStore, StoreError, StoreHooks
from airprompter_agent_core.control.client import SyncClient
from airprompter_agent_sync.sync.daemon import DAEMON_MAX_LINE_BYTES, DaemonClient, DaemonError, DaemonHello, daemon_socket_path
from airprompter_agent_sync.sync.loop import SyncPassOutput, jittered_delay_ms, sync_once
from airprompter_agent_core.checks import CHECK_BOUNDS, check_refusal, checks_refusals, estimate_tokens, evaluate_check, evaluate_checks, output_text_of, pattern_refusal, project_checks, validate_json_schema, value_at_path
from airprompter_agent_runtime.inference import INFERENCE_KEYS, AppliedInference, apply_inference, temperature_of, top_p_of
from airprompter_agent_runtime.observe import ObserveTarget, UsageNormalized, classify_error, classify_result, normalize_usage, observe_call, observe_call_async
from airprompter_agent_runtime.variables import (
    DEFAULT_SOURCE_MAX_BYTES,
    DEFAULT_SOURCE_TIMEOUT_SECONDS,
    FilledRender,
    FillPlan,
    VariableSource,
    VariableSourceContext,
    VariableSourceError,
    VariableSourceRegistry,
    VariableSourceRequiredError,
    fill_async,
    fill_sync,
    is_variable_source_error,
    is_variable_source_required_error,
    plan_fill,
    stricter_sources,
    unsourced,
)
from airprompter_agent_telemetry.uploader import GrantDecision, PassResult, SpoolUploader, UploadGrant, backoff_delay_ms, inspect_segment, post_segment, validate_spool_row

# S10: the seam between the packages and the runtime over it, for a customer who holds a release and wants no store.
from airprompter_agent_core.release.bundle_release import BundleRelease, BundleReleaseRefused
from airprompter_agent_core.release.reader import LoadedRelease, ReleaseReader, ReleaseSlot
from airprompter_agent_runtime.release.resolver import Disabled, ReleaseResolver, ResolveOutcome, disabled_from

__version__ = SDK_VERSION

__all__ = [
    "APBUNDLE_INFO",
    "AppliedInference",
    "INFERENCE_KEYS",
    "apply_inference",
    "temperature_of",
    "top_p_of",
    "ASSIGNMENT_MODULUS",
    "AgentStartError",
    "AgentStatus",
    "AirPrompterAgent",
    "ApplyOptions",
    "Assignment",
    "AssignmentError",
    "BundleError",
    "BundleRelease",
    "BundleReleaseRefused",
    "CHECK_BOUNDS",
    "CanonicalJsonError",
    "DAEMON_MAX_LINE_BYTES",
    "DaemonClient",
    "DaemonError",
    "DaemonHello",
    "Delimiters",
    "DirectorySink",
    "Disabled",
    "DistributionKey",
    "ERROR_CLASSES",
    "GOLDEN_SET_FORMAT",
    "GOLDEN_SET_VERSION",
    "GoldenCaseResult",
    "GoldenInvocation",
    "GoldenOptions",
    "GoldenReport",
    "GoldenSetError",
    "GrantDecision",
    "HOST_SPOOL_BUDGET_BYTES",
    "JUDGE_RUBRICS",
    "JudgeResult",
    "JudgeRubric",
    "KeyProvider",
    "LATENCY_BUCKET_EDGES_MS",
    "LoadedRelease",
    "LoadedSlot",
    "MANAGED_REFUSAL_CODES",
    "MANAGED_SDK_USER_AGENT",
    "ManagedAgent",
    "ManagedRunError",
    "ManagedRunResult",
    "ManagedRunStream",
    "ManagedWorkflow",
    "MemorySink",
    "MissingVariableError",
    "NormalizedFeedback",
    "Observation",
    "ObserveTarget",
    "PROTECTION_CRITERIA",
    "PROTOCOL_VERSION",
    "PassResult",
    "PayloadDecryptError",
    "PromptHandle",
    "ReleaseChange",
    "ReleaseReader",
    "ReleaseResolver",
    "ReleaseSlot",
    "RenderRefusedError",
    "Rendered",
    "ResolveOutcome",
    "RunRefFacts",
    "SDK_NAME",
    "SDK_VERSION",
    "SEGMENT_MAX_BYTES",
    "SERVERLESS_BUFFER_BYTES",
    "SegmentPlanner",
    "SlotStore",
    "SpoolSink",
    "SpoolUploader",
    "SpoolWriter",
    "StagedRelease",
    "StepError",
    "StoreError",
    "StoreHooks",
    "SyncClient",
    "SyncOptions",
    "SyncPassOutput",
    "TelemetryOptions",
    "UNDEFINED",
    "UnknownVariableError",
    "UpdateWindow",
    "UploadGrant",
    "UsageNormalized",
    "VendoredBundle",
    "Verdict",
    "WindowState",
    "Workflow",
    "WorkflowHandle",
    "WorkflowStep",
    "DEFAULT_SOURCE_MAX_BYTES",
    "DEFAULT_SOURCE_TIMEOUT_SECONDS",
    "FilledRender",
    "FillPlan",
    "VariableSource",
    "VariableSourceContext",
    "VariableSourceError",
    "VariableSourceRegistry",
    "VariableSourceRequiredError",
    "fill_async",
    "fill_sync",
    "is_variable_source_error",
    "is_variable_source_required_error",
    "plan_fill",
    "stricter_sources",
    "unsourced",
    "WriterIdentity",
    "X25519KeyPair",
    "agent",
    "apply",
    "arm_for_bucket",
    "assign_arm",
    "backoff_delay_ms",
    "bucket_from_hash",
    "bundle",
    "bundle_payload_bytes",
    "canonical_bytes",
    "canonical_json",
    "check_refusal",
    "checks_refusals",
    "classify_error",
    "classify_result",
    "create_encrypted_bundle",
    "create_plaintext_bundle",
    "custom_key_provider",
    "daemon_socket_path",
    "decrypt_payload",
    "default_state_dir",
    "disabled_from",
    "distribution_key_id",
    "encrypt_payload",
    "epoch_minute",
    "estimate_tokens",
    "evaluate_check",
    "evaluate_checks",
    "file_key",
    "generate_p256_jwk",
    "generate_x25519_key_pair",
    "golden_reports_meet",
    "healthz_of",
    "healthz_response",
    "inspect_segment",
    "is_known_time_zone",
    "jittered_delay_ms",
    "judge_prompt",
    "judge_signals_of",
    "key_thumbprint",
    "kms",
    "latency_bucket_index",
    "managed",
    "mint_run_ref",
    "minute_of",
    "normalize_feedback",
    "normalize_usage",
    "observe_call",
    "observe_call_async",
    "open_bundle",
    "ordered_steps",
    "os_keystore",
    "output_text_of",
    "parse_golden_set",
    "parse_judge_reply",
    "parse_run_ref",
    "parse_sse",
    "parse_window",
    "pass_bps_of",
    "pattern_refusal",
    "payload_aad",
    "post_segment",
    "project_checks",
    "protocol",
    "public_jwk_of",
    "referenced_payloads",
    "release_digest",
    "release_digest_input",
    "render",
    "render_template",
    "rubric_from_prompt",
    "run_golden_set",
    "segment_name",
    "sha256_prefixed",
    "sign_bytes",
    "spool",
    "store",
    "subject_hash",
    "sync",
    "sync_once",
    "telemetry",
    "trusted_root_from_pinned_key",
    "unwrap_with_raw_key",
    "validate_arms",
    "validate_json_schema",
    "validate_spool_row",
    "validate_window",
    "value_at_path",
    "vault",
    "verify_bytes",
    "verify_manifest",
    "verify_root_metadata",
    "window_state",
    "wrap_with_raw_key",
    "x25519_private_key_from_raw",
    "x25519_public_key_from_raw",
    "xml_delimiters",
]
